import type { Briefing, IssuedWorkerLink, LocalizedWorkerContext, NationalityCode, OverrideReason, OwnerWorkSession, Quantity, QuantityChangePreview, TeamMember, TodayWorkTeam, Translation, WorkDraft, WorkerAssignment, WorkerStep, WorkState } from './contracts';
import type { WorkerLocale } from './model';

type ApiErrorConstructor = new (status: number, code: 'UNAUTHORIZED' | 'NOT_FOUND' | 'ACCESS_DENIED' | 'LINK_EXPIRED' | 'VERSION_CONFLICT', message: string) => Error;
const SESSION_KEY = 'batmeori-demo-session-v2';
const TEAM_KEY = 'batmeori-demo-today-team-v2';
const DEMO_TEAM_TOKEN = 'demo-today-team';
const translated = (language_code: WorkerLocale, segment: Translation['segment'], text: string): Translation => ({ language_code, segment, text, source: 'AI_TRANSLATION', verified: false, guide_lookup: 'MISS', phrase_key: null, source_page: null, source_url: null, license: null });
const onionSteps = [
  { sequence: 1, task_code: 'ONION_HARVEST' as const, title_ko: '양파 수확', description_ko: '양파가 상하지 않게 흙에서 꺼냅니다.', video: null, audio_url: null, delivery_mode: 'TEXT_TTS' as const, unsupported_reason: null, translations: [translated('vi', 'ACTION', 'Nhổ hành tây nhẹ nhàng để không làm dập củ'), translated('ne', 'ACTION', 'प्याज नबिग्रिने गरी बिस्तारै निकाल्नुहोस्')] },
  { sequence: 2, task_code: 'ONION_TRIMMING' as const, title_ko: '양파 손질', description_ko: '마른 줄기와 뿌리를 잘라 손질합니다.', video: null, audio_url: null, delivery_mode: 'TEXT_TTS' as const, unsupported_reason: null, translations: [translated('vi', 'ACTION', 'Cắt bỏ lá khô và rễ của hành tây'), translated('ne', 'ACTION', 'प्याजका सुकेका पात र जरा काट्नुहोस्')] },
  { sequence: 3, task_code: 'ONION_SORTING' as const, title_ko: '양파 분류', description_ko: '상하거나 다친 양파를 골라 따로 둡니다.', video: null, audio_url: null, delivery_mode: 'TEXT_TTS' as const, unsupported_reason: null, translations: [translated('vi', 'ACTION', 'Phân loại riêng những củ hành bị hỏng'), translated('ne', 'ACTION', 'बिग्रेका प्याज छुट्टै वर्गीकरण गर्नुहोस्')] },
  { sequence: 4, task_code: 'ONION_TRANSPORT' as const, title_ko: '양파 운반', description_ko: '분류한 양파를 집하장으로 손수 옮깁니다.', video: null, audio_url: null, delivery_mode: 'TEXT_TTS' as const, unsupported_reason: null, translations: [translated('vi', 'ACTION', 'Mang hành đã phân loại đến điểm tập kết bằng tay'), translated('ne', 'ACTION', 'वर्गीकरण गरिएको प्याज हातैले सङ्कलन स्थानमा लैजानुहोस्')] },
];
const strawberrySteps = [
  { sequence: 1, task_code: 'STRAWBERRY_HARVEST' as const, title_ko: '딸기 수확', description_ko: '잘 익은 딸기를 눌리지 않게 수확합니다.', video: null, audio_url: null, delivery_mode: 'TEXT_TTS' as const, unsupported_reason: null, translations: [translated('vi', 'ACTION', 'Hái dâu tây chín nhẹ nhàng để không bị dập'), translated('ne', 'ACTION', 'पाकेको स्ट्रबेरी नथिचिने गरी बिस्तारै टिप्नुहोस्')] },
  { sequence: 2, task_code: 'STRAWBERRY_SORTING' as const, title_ko: '딸기 분류', description_ko: '크기와 상태에 따라 딸기를 나눕니다.', video: null, audio_url: null, delivery_mode: 'TEXT_TTS' as const, unsupported_reason: null, translations: [translated('vi', 'ACTION', 'Phân loại dâu tây theo kích thước và tình trạng'), translated('ne', 'ACTION', 'आकार र अवस्थाअनुसार स्ट्रबेरी छुट्याउनुहोस्')] },
  { sequence: 3, task_code: 'STRAWBERRY_INSPECTION' as const, title_ko: '딸기 검수', description_ko: '무르거나 상한 딸기를 골라냅니다.', video: null, audio_url: null, delivery_mode: 'TEXT_TTS' as const, unsupported_reason: null, translations: [translated('vi', 'ACTION', 'Loại riêng những quả dâu mềm hoặc bị hỏng'), translated('ne', 'ACTION', 'नरम वा बिग्रेको स्ट्रबेरी अलग गर्नुहोस्')] },
  { sequence: 4, task_code: 'STRAWBERRY_PACKING' as const, title_ko: '딸기 포장', description_ko: '검수한 딸기를 포장 용기에 가지런히 담습니다.', video: null, audio_url: null, delivery_mode: 'TEXT_TTS' as const, unsupported_reason: null, translations: [translated('vi', 'ACTION', 'Xếp dâu đã kiểm tra ngay ngắn vào hộp'), translated('ne', 'ACTION', 'जाँच गरिएको स्ट्रबेरी प्याकिङ बाकसमा मिलाएर राख्नुहोस्')] },
];
const draft = (family: 'ONION' | 'STRAWBERRY' = 'ONION'): WorkDraft => family === 'ONION'
  ? { draft_id: 'draft-demo-onion', draft_revision: 0, summary_ko: '1번 밭에서 양파 20망을 수확하고 손질·분류한 뒤 집하장으로 손수 운반합니다.', interpretation: 'READY', state: { task_family: 'ONION', location: { raw_text: '1번 밭', kind: 'NAMED', canonical_name: '1번 밭' }, location_display: '1번 밭', quantity: { value: 20, unit: '망' }, deadline: '오전 11시', safety: [], notes: '상한 양파는 따로 모아주세요.', steps: onionSteps }, ambiguities: [], risk_assessment: { level: 'LOW', reasons: [], schema_version: '1', contract_version: 'safety-policy-v1' }, transcript: '1번 밭 양파 스무 망 캐서 손질하고 분류한 다음 집하장으로 손수 옮겨. 오전 열한 시까지.', schema_version: '1', contract_version: 'structure-v1' }
  : { draft_id: 'draft-demo-strawberry', draft_revision: 0, summary_ko: '2번 하우스에서 딸기 15상자를 수확하고 분류·검수한 뒤 포장합니다.', interpretation: 'READY', state: { task_family: 'STRAWBERRY', location: { raw_text: '2번 하우스', kind: 'NAMED', canonical_name: '2번 하우스' }, location_display: '2번 하우스', quantity: { value: 15, unit: '상자' }, deadline: '오전 10시', safety: [], notes: '무른 딸기는 따로 담아주세요.', steps: strawberrySteps }, ambiguities: [], risk_assessment: { level: 'LOW', reasons: [], schema_version: '1', contract_version: 'safety-policy-v1' }, transcript: '2번 하우스 딸기 열다섯 상자 따서 분류하고 검수한 다음 포장해. 오전 열 시까지.', schema_version: '1', contract_version: 'structure-v1' };
let currentDraft = draft();
const loadSession = () => { const saved = window.localStorage.getItem(SESSION_KEY); return saved ? JSON.parse(saved) as OwnerWorkSession : null; };
const saveSession = (session: OwnerWorkSession) => { window.localStorage.setItem(SESSION_KEY, JSON.stringify(session)); return session; };
const createSession = (state: WorkState = currentDraft.state, version = 1): OwnerWorkSession => ({ session_id: 'work-demo-01', current_version: version, lifecycle: 'PUBLISHED', version: { version, lifecycle: 'PUBLISHED', state, risk_assessment: currentDraft.risk_assessment, transcript: currentDraft.transcript } });
const wait = <T>(value: T) => new Promise<T>((resolve) => window.setTimeout(() => resolve(value), 250));
const loadTeam = () => { const saved = window.localStorage.getItem(TEAM_KEY); return saved ? { ...(JSON.parse(saved) as TodayWorkTeam), status: 'ACTIVE' as const } : null; };
const saveTeam = (team: TodayWorkTeam) => { window.localStorage.setItem(TEAM_KEY, JSON.stringify(team)); return team; };
const createTeam = () => { const now = new Date(); const dayEnd = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1); const expires = new Date(Math.min(now.getTime() + 24 * 60 * 60_000, dayEnd.getTime())); return saveTeam({ team_id: crypto.randomUUID(), work_date: now.toLocaleDateString('sv-SE'), status: 'ACTIVE', join_url: `${window.location.origin}/team/${DEMO_TEAM_TOKEN}`, expires_at: expires.toISOString(), members: [] }); };
const contextFor = (locale: WorkerLocale, session: OwnerWorkSession): LocalizedWorkerContext => {
  const quantity = session.version.state.quantity;
  const strawberry = session.version.state.task_family === 'STRAWBERRY';
  const amount = typeof quantity === 'object' && quantity ? `${quantity.value} ${strawberry ? (locale === 'vi' ? 'hộp' : 'बाकस') : (locale === 'vi' ? 'bao' : 'बोरा')}` : locale === 'vi' ? 'Chưa xác định' : 'तोकिएको छैन';
  if (strawberry) return locale === 'vi'
    ? { location_display: 'Nhà kính số 2', quantity_display: amount, deadline_display: 'Trước 10 giờ sáng', safety: [], notes: 'Để riêng dâu mềm.' }
    : { location_display: 'ग्रीनहाउस नम्बर २', quantity_display: amount, deadline_display: 'बिहान १० बजेसम्म', safety: [], notes: 'नरम स्ट्रबेरी अलग राख्नुहोस्।' };
  return locale === 'vi'
    ? { location_display: 'Ruộng số 1', quantity_display: amount, deadline_display: 'Trước 11 giờ sáng', safety: [], notes: 'Để riêng hành bị hỏng.' }
    : { location_display: 'खेत नम्बर १', quantity_display: amount, deadline_display: 'बिहान ११ बजेसम्म', safety: [], notes: 'बिग्रेको प्याज अलग राख्नुहोस्।' };
};
const workerSteps = (locale: WorkerLocale, session: OwnerWorkSession): WorkerStep[] => session.version.state.steps.map((step) => { const segments = step.translations.filter((item) => item.language_code === locale); const description = segments.map((item) => item.text).join('. '); return { sequence: step.sequence, task_code: step.task_code, title: description, description, video: step.video, audio_url: step.audio_url, delivery_mode: step.delivery_mode, unsupported_reason: null, segments }; });

export function createMockApi(ApiError: ApiErrorConstructor) {
  return {
    createOwnerSession: () => wait({ authenticated: true as const, expires_at: new Date(Date.now() + 60 * 60_000).toISOString() }),
    createDraft: async (audio: Blob) => { currentDraft = draft((await audio.text()).includes('strawberry') ? 'STRAWBERRY' : 'ONION'); return wait(currentDraft); },
    supplementDraft: (_draftId: string, _audio: Blob, expectedRevision: number) => { currentDraft = { ...currentDraft, draft_revision: expectedRevision + 1, interpretation: 'READY', ambiguities: [] }; return wait(currentDraft); },
    confirmDraft: (_draftId: string, _decision: 'CONFIRM' | 'PUBLISH_AS_IS', _reason?: OverrideReason) => wait(saveSession(createSession())),
    listSessions: () => wait({ items: loadSession() ? [loadSession()!] : [] }),
    getSession: (sessionId: string) => { const session = loadSession(); return session?.session_id === sessionId ? wait(session) : Promise.reject(new ApiError(404, 'NOT_FOUND', '작업을 찾을 수 없습니다.')); },
    parseQuantityChange: (_sessionId: string, _audio: Blob, expectedVersion: number): Promise<QuantityChangePreview> => wait({ interpretation: 'READY', quantity: { value: 15, unit: '망' }, expected_version: expectedVersion, ambiguities: [], schema_version: '1', contract_version: 'quantity-change-v1' }),
    confirmQuantityChange: (_sessionId: string, quantity: Quantity, expectedVersion: number) => { const session = loadSession(); if (!session || session.current_version !== expectedVersion) return Promise.reject(new ApiError(409, 'VERSION_CONFLICT', '최신 작업 버전을 다시 확인하세요.')); return wait(saveSession(createSession({ ...session.version.state, quantity }, expectedVersion + 1))); },
    issueWorkerLink: (sessionId: string, languageCode: WorkerLocale): Promise<IssuedWorkerLink> => { const token = `demo-${languageCode}-${crypto.randomUUID().replace(/-/g, '')}`; return wait({ session_id: sessionId, issued_worker_link: { language_code: languageCode, url: `${window.location.origin}/w/${token}`, expires_at: new Date(Date.now() + 24 * 60 * 60_000).toISOString() } }); },
    getAssignment: (token: string): Promise<WorkerAssignment> => { if (token.includes('expired')) return Promise.reject(new ApiError(410, 'LINK_EXPIRED', '접근할 수 없습니다.')); if (!token.startsWith('demo-')) return Promise.reject(new ApiError(404, 'ACCESS_DENIED', '접근할 수 없습니다.')); const session = loadSession() ?? saveSession(createSession()); const language_code: WorkerLocale = token.startsWith('demo-ne-') ? 'ne' : 'vi'; return wait({ language_code, session_id: session.session_id, version: session.current_version, lifecycle: 'PUBLISHED', context: contextFor(language_code, session), steps: workerSteps(language_code, session), badge_codes: ['DEMO_FALLBACK'] }); },
    getBriefing: (sessionId: string, languageCode: WorkerLocale): Promise<Briefing> => { const session = loadSession(); if (!session || session.session_id !== sessionId) return Promise.reject(new ApiError(404, 'NOT_FOUND', '작업을 찾을 수 없습니다.')); return wait({ session_id: sessionId, version: session.current_version, language_code: languageCode, context: contextFor(languageCode, session), steps: workerSteps(languageCode, session), badge_codes: ['DEMO_FALLBACK'] }); },
    createTodayTeam: (): Promise<TodayWorkTeam> => { const existing = loadTeam(); return wait(existing && new Date(existing.expires_at) > new Date() ? existing : createTeam()); },
    getTodayTeam: (): Promise<TodayWorkTeam> => { const team = loadTeam(); return team ? wait(team) : Promise.reject(new ApiError(404, 'NOT_FOUND', '오늘 작업팀이 아직 없습니다.')); },
    joinTodayTeam: (token: string, input: { display_name: string; nationality_code: NationalityCode; language_code: WorkerLocale }): Promise<TeamMember> => { const saved = loadTeam(); const team = token === DEMO_TEAM_TOKEN && (!saved || new Date(saved.expires_at) <= new Date()) ? createTeam() : saved; if (!team || !team.join_url.endsWith(`/team/${token}`)) return Promise.reject(new ApiError(404, 'ACCESS_DENIED', '참여 코드를 확인해주세요.')); if (new Date(team.expires_at) <= new Date()) return Promise.reject(new ApiError(410, 'LINK_EXPIRED', '참여 시간이 끝났습니다.')); const member = { member_id: crypto.randomUUID(), ...input, joined_at: new Date().toISOString() }; saveTeam({ ...team, members: [...team.members, member] }); return wait(member); },
  };
}
