import { AlertCircle, ArrowLeft, ArrowRight, Camera, Check, ChevronDown, ChevronLeft, ChevronRight, Clock3, Link2Off, ShieldAlert, UserRound, Volume2 } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { api, ApiError, isMockApi } from './api';
import type { NationalityCode, TeamMember, WorkerAssignment, WorkerBadgeCode, WorkerStep } from './contracts';
import type { AppScreen, ScreenProps, WorkerLocale } from './model';
import type { Locale } from '../types';
import { ActionButton, Callout, FactRow, PageHeading, Panel, PanelHeader, ProgressBar, StatusBadge } from './ScreenUI';

interface WorkerScreenProps extends ScreenProps { screen: AppScreen; token: string | null; locale: WorkerLocale; entryLocale: Locale; setLocale: (locale: WorkerLocale) => void; }
const labels = {
  vi: { latest: 'Công việc mới nhất', today: 'Công việc hôm nay', location: 'Địa điểm', amount: 'Số lượng', deadline: 'Hoàn thành', note: 'Ghi chú', safety: 'An toàn', listen: 'Nghe hướng dẫn', view: 'Xem từng bước', prev: 'Trước', next: 'Tiếp theo', understood: 'Đã hiểu', fallback: 'Không có video đã kiểm duyệt. Hãy đọc hoặc nghe hướng dẫn.', unavailable: 'Không thể mở đường dẫn', expired: 'Đường dẫn đã hết hạn. Hãy xin chủ nông trại gửi lại đường dẫn mới.', invalid: 'Không thể truy cập. Hãy kiểm tra đường dẫn hoặc hỏi chủ nông trại.', stale: 'Không thể kiểm tra hướng dẫn mới nhất. Nội dung bên dưới có thể đã cũ.', retry: 'Thử lại', updated: 'Có hướng dẫn mới. Hãy xem lại từ bước đầu tiên.', audioFailed: 'Không thể phát giọng nói. Hãy đọc nội dung bên dưới.', needs: 'Cần xác nhận với chủ nông trại', demo: 'NỘI DUNG DEMO' },
  ne: { latest: 'नयाँ काम', today: 'आजको काम', location: 'स्थान', amount: 'परिमाण', deadline: 'समय सीमा', note: 'टिप्पणी', safety: 'सुरक्षा', listen: 'निर्देशन सुन्नुहोस्', view: 'चरणहरू हेर्नुहोस्', prev: 'अघिल्लो', next: 'अर्को', understood: 'बुझें', fallback: 'जाँच गरिएको भिडियो छैन। निर्देशन पढ्नुहोस् वा सुन्नुहोस्।', unavailable: 'लिङ्क खोल्न सकिएन', expired: 'लिङ्कको म्याद सकिएको छ। खेत मालिकसँग नयाँ लिङ्क माग्नुहोस्।', invalid: 'पहुँच गर्न सकिएन। लिङ्क जाँच्नुहोस् वा खेत मालिकलाई सोध्नुहोस्।', stale: 'नयाँ निर्देशन जाँच्न सकिएन। तलको जानकारी पुरानो हुन सक्छ।', retry: 'फेरि प्रयास', updated: 'नयाँ निर्देशन आएको छ। पहिलो चरणदेखि फेरि हेर्नुहोस्।', audioFailed: 'आवाज बजाउन सकिएन। तलको निर्देशन पढ्नुहोस्।', needs: 'खेत मालिकसँग पुष्टि गर्नुहोस्', demo: 'डेमो सामग्री' },
  km: { latest: 'ការងារថ្មីបំផុត', today: 'ការងារថ្ងៃនេះ', location: 'ទីតាំង', amount: 'បរិមាណ', deadline: 'ពេលបញ្ចប់', note: 'កំណត់សម្គាល់', safety: 'សុវត្ថិភាព', listen: 'ស្តាប់សេចក្តីណែនាំ', view: 'មើលតាមជំហាន', prev: 'មុន', next: 'បន្ទាប់', understood: 'យល់ហើយ', fallback: 'មិនមានវីដេអូដែលបានត្រួតពិនិត្យទេ។ សូមអាន ឬស្តាប់សេចក្តីណែនាំ។', unavailable: 'មិនអាចបើកតំណបាន', expired: 'តំណបានផុតកំណត់។ សូមស្នើម្ចាស់កសិដ្ឋានឱ្យផ្ញើតំណថ្មី។', invalid: 'មិនអាចចូលមើលបាន។ សូមពិនិត្យតំណ ឬសួរម្ចាស់កសិដ្ឋាន។', stale: 'មិនអាចពិនិត្យសេចក្តីណែនាំថ្មីបំផុតបានទេ។ ខ្លឹមសារខាងក្រោមអាចចាស់។', retry: 'ព្យាយាមម្តងទៀត', updated: 'មានសេចក្តីណែនាំថ្មី។ សូមមើលឡើងវិញចាប់ពីជំហានទីមួយ។', audioFailed: 'មិនអាចចាក់សំឡេងបានទេ។ សូមអានសេចក្តីណែនាំខាងក្រោម។', needs: 'ត្រូវបញ្ជាក់ជាមួយម្ចាស់កសិដ្ឋាន', demo: 'ខ្លឹមសារសាកល្បង' },
};

const languageNames: Record<WorkerLocale, string> = { vi: 'Tiếng Việt', ne: 'नेपाली', km: 'ភាសាខ្មែរ' };
const speechLocales: Record<WorkerLocale, string> = { vi: 'vi-VN', ne: 'ne-NP', km: 'km-KH' };
const stepNames: Record<WorkerLocale, { step: string; list: string }> = {
  vi: { step: 'Bước', list: 'Danh sách' }, ne: { step: 'चरण', list: 'सूची' }, km: { step: 'ជំហាន', list: 'បញ្ជី' },
};

const badgeText = (locale: WorkerLocale, badge: WorkerBadgeCode) => badge === 'NEEDS_CONFIRMATION' ? labels[locale].needs : labels[locale].demo;
const playableVideo = (step: WorkerStep) => step.video?.review_status === 'APPROVED' && step.video.safety_level === 'LOW' ? step.video : null;
const captionsUrl = (text: string) => `data:text/vtt;charset=utf-8,${encodeURIComponent(`WEBVTT\n\n00:00.000 --> 23:59.000\n${text.replace(/\n/g, ' ')}`)}`;

function SpeakButton({ step, locale, className = '' }: { step: WorkerStep; locale: WorkerLocale; className?: string }) {
  const [speaking, setSpeaking] = useState(false); const [failed, setFailed] = useState(false); const audio = useRef<HTMLAudioElement | null>(null);
  const browserSpeech = () => { if (!window.speechSynthesis) { setFailed(true); setSpeaking(false); return; } const speech = new SpeechSynthesisUtterance(step.description); speech.lang = speechLocales[locale]; speech.onend = () => setSpeaking(false); speech.onerror = () => { setSpeaking(false); setFailed(true); }; window.speechSynthesis.cancel(); window.speechSynthesis.speak(speech); };
  const play = async () => { setFailed(false); setSpeaking(true); window.speechSynthesis.cancel(); audio.current?.pause(); if (!step.audio_url) { browserSpeech(); return; } const next = new Audio(step.audio_url); audio.current = next; next.onended = () => setSpeaking(false); next.onerror = browserSpeech; try { await next.play(); } catch { browserSpeech(); } };
  useEffect(() => () => { audio.current?.pause(); window.speechSynthesis.cancel(); }, [step.sequence, step.description]);
  return <div className={className}><ActionButton className="w-full" onClick={play}><Volume2 className={`h-5 w-5 ${speaking ? 'animate-pulse' : ''}`} />{labels[locale].listen}</ActionButton>{failed && <p role="alert" className="mt-3 text-base font-extrabold text-[#8A302B]">{labels[locale].audioFailed}</p>}</div>;
}

const entryCopy = {
  ko: { countryTitle: '국적을 선택하세요', countryDescription: '본인의 국적을 골라주세요.', inviteTitle: '농장주의 QR을 찍으세요', inviteDescription: 'QR을 찍어도 바로 이동하지 않습니다. 국적과 이름을 입력한 뒤 참여합니다.', profileTitle: '이름을 알려주세요', profileDescription: '농장주가 알아볼 수 있는 이름이나 별명을 적어주세요.', name: '이름 또는 별명', nameHint: '예: 응우옌', country: '국적', scan: 'QR 코드 스캔', stop: '카메라 닫기', link: '팀 참여 링크 또는 코드', testLink: '테스트 링크 사용', testHelp: 'QR 테스트가 어려우면 아래 링크를 사용하세요.', next: '다음', back: '이전', join: '오늘 작업팀 들어가기', joined: '작업팀에 들어왔어요', wait: '농장주의 작업 지시를 기다려주세요.', camera: '카메라를 사용할 수 없습니다. 아래에 링크나 코드를 입력하세요.', countryError: '국적을 선택해주세요.', inviteError: '올바른 참여 링크 또는 코드를 확인해주세요.', nameError: '이름 또는 별명을 입력해주세요.' },
  vi: { countryTitle: 'Chọn quốc tịch', countryDescription: 'Hãy chọn quốc tịch của bạn.', inviteTitle: 'Quét mã QR của chủ nông trại', inviteDescription: 'Quét QR sẽ không chuyển trang ngay. Bạn sẽ tham gia sau khi chọn quốc tịch và nhập tên.', profileTitle: 'Cho chúng tôi biết tên của bạn', profileDescription: 'Nhập tên hoặc biệt danh để chủ nông trại nhận ra bạn.', name: 'Tên hoặc biệt danh', nameHint: 'Ví dụ: Nguyễn', country: 'Quốc tịch', scan: 'Quét mã QR', stop: 'Đóng camera', link: 'Đường dẫn hoặc mã tham gia', testLink: 'Dùng liên kết thử nghiệm', testHelp: 'Nếu khó quét QR, hãy dùng liên kết bên dưới.', next: 'Tiếp theo', back: 'Quay lại', join: 'Tham gia nhóm hôm nay', joined: 'Bạn đã vào nhóm', wait: 'Hãy chờ chủ nông trại gửi hướng dẫn.', camera: 'Không thể dùng camera. Hãy nhập đường dẫn hoặc mã bên dưới.', countryError: 'Hãy chọn quốc tịch.', inviteError: 'Hãy kiểm tra đường dẫn hoặc mã tham gia.', nameError: 'Hãy nhập tên hoặc biệt danh.' },
  ne: { countryTitle: 'राष्ट्रियता छान्नुहोस्', countryDescription: 'आफ्नो राष्ट्रियता छान्नुहोस्।', inviteTitle: 'खेत मालिकको QR स्क्यान गर्नुहोस्', inviteDescription: 'QR स्क्यान गरेपछि तुरुन्त अर्को पृष्ठ खुल्दैन। राष्ट्रियता छानेर नाम लेखेपछि मात्र सहभागी हुनुहुन्छ।', profileTitle: 'तपाईंको नाम लेख्नुहोस्', profileDescription: 'खेत मालिकले चिन्न सक्ने नाम वा उपनाम लेख्नुहोस्।', name: 'नाम वा उपनाम', nameHint: 'उदाहरण: रमेश', country: 'राष्ट्रियता', scan: 'QR कोड स्क्यान', stop: 'क्यामेरा बन्द', link: 'टोली लिङ्क वा कोड', testLink: 'परीक्षण लिङ्क प्रयोग गर्नुहोस्', testHelp: 'QR स्क्यान गर्न गाह्रो भए तलको लिङ्क प्रयोग गर्नुहोस्।', next: 'अर्को', back: 'अघिल्लो', join: 'आजको टोलीमा सामेल', joined: 'तपाईं टोलीमा सामेल हुनुभयो', wait: 'खेत मालिकको निर्देशन पर्खनुहोस्।', camera: 'क्यामेरा चलाउन सकिएन। तल लिङ्क वा कोड लेख्नुहोस्।', countryError: 'राष्ट्रियता छान्नुहोस्।', inviteError: 'सहभागिता लिङ्क वा कोड जाँच्नुहोस्।', nameError: 'नाम वा उपनाम लेख्नुहोस्।' },
  km: { countryTitle: 'ជ្រើសរើសសញ្ជាតិ', countryDescription: 'សូមជ្រើសរើសសញ្ជាតិរបស់អ្នក។', inviteTitle: 'ស្កេន QR របស់ម្ចាស់កសិដ្ឋាន', inviteDescription: 'ការស្កេន QR មិននាំអ្នកទៅទំព័រផ្សេងភ្លាមៗទេ។ អ្នកនឹងចូលរួមបន្ទាប់ពីជ្រើសរើសសញ្ជាតិ និងបញ្ចូលឈ្មោះ។', profileTitle: 'សូមប្រាប់ឈ្មោះរបស់អ្នក', profileDescription: 'បញ្ចូលឈ្មោះ ឬឈ្មោះហៅក្រៅដែលម្ចាស់កសិដ្ឋានអាចស្គាល់បាន។', name: 'ឈ្មោះ ឬឈ្មោះហៅក្រៅ', nameHint: 'ឧទាហរណ៍៖ សុខា', country: 'សញ្ជាតិ', scan: 'ស្កេនកូដ QR', stop: 'បិទកាមេរ៉ា', link: 'តំណ ឬលេខកូដចូលរួមក្រុម', testLink: 'ប្រើតំណសាកល្បង', testHelp: 'បើពិបាកស្កេន QR សូមប្រើតំណខាងក្រោម។', next: 'បន្ទាប់', back: 'ត្រឡប់ក្រោយ', join: 'ចូលរួមក្រុមថ្ងៃនេះ', joined: 'អ្នកបានចូលរួមក្រុមហើយ', wait: 'សូមរង់ចាំសេចក្តីណែនាំពីម្ចាស់កសិដ្ឋាន។', camera: 'មិនអាចប្រើកាមេរ៉ាបានទេ។ សូមបញ្ចូលតំណ ឬលេខកូដខាងក្រោម។', countryError: 'សូមជ្រើសរើសសញ្ជាតិ។', inviteError: 'សូមពិនិត្យតំណ ឬលេខកូដចូលរួម។', nameError: 'សូមបញ្ចូលឈ្មោះ ឬឈ្មោះហៅក្រៅ។' },
};

const countries: Array<{ code: NationalityCode; name: string }> = [
  { code: 'VN', name: 'Vietnam' }, { code: 'PH', name: 'Philippines' },
  { code: 'LA', name: 'Laos' }, { code: 'KH', name: 'Cambodia' },
  { code: 'TH', name: 'Thailand' }, { code: 'NP', name: 'Nepal' },
  { code: 'MM', name: 'Myanmar' }, { code: 'MN', name: 'Mongolia' },
];
const nationalityLocales: Partial<Record<NationalityCode, WorkerLocale>> = { VN: 'vi', NP: 'ne', KH: 'km' };
const TEST_TEAM_TOKEN = 'demo-today-team';
const extractToken = (value: string, kind: 'team' | 'work') => value.trim().match(new RegExp(`/${kind === 'team' ? 'team' : 'w'}/([^/?#]+)`))?.[1] ?? (value.trim().length >= 32 ? value.trim() : '');

function WorkerEntry({ locale, workerLocale, setLocale, go }: { locale: Locale; workerLocale: WorkerLocale; setLocale: (locale: WorkerLocale) => void; go: ScreenProps['go'] }) {
  const directToken = extractToken(window.location.href, 'team'); const [phase, setPhase] = useState<'invite' | 'country' | 'profile'>('invite'); const [value, setValue] = useState(directToken); const [name, setName] = useState(''); const [country, setCountry] = useState<NationalityCode | ''>(''); const [error, setError] = useState(''); const [joined, setJoined] = useState<TeamMember | null>(null); const [scanning, setScanning] = useState(false); const [loading, setLoading] = useState(false); const video = useRef<HTMLVideoElement | null>(null); const stream = useRef<MediaStream | null>(null); const t = entryCopy[phase === 'profile' ? workerLocale : locale]; const testTeamLink = `${window.location.origin}/team/${TEST_TEAM_TOKEN}`;
  const stop = () => { stream.current?.getTracks().forEach((track) => track.stop()); stream.current = null; setScanning(false); };
  useEffect(() => stop, []);
  const scan = async () => {
    if (scanning) { stop(); return; }
    const Detector = (window as unknown as { BarcodeDetector?: new (options: { formats: string[] }) => { detect(source: HTMLVideoElement): Promise<Array<{ rawValue: string }>> } }).BarcodeDetector;
    if (!Detector || !navigator.mediaDevices?.getUserMedia) { setError(t.camera); return; }
    try { setError(''); const media = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } }); stream.current = media; setScanning(true); window.setTimeout(async () => { if (!video.current) return; video.current.srcObject = media; await video.current.play(); const detector = new Detector({ formats: ['qr_code'] }); const timer = window.setInterval(async () => { if (!video.current || !stream.current) { window.clearInterval(timer); return; } const result = await detector.detect(video.current).catch(() => []); if (result[0]?.rawValue) { const teamToken = extractToken(result[0].rawValue, 'team'); if (teamToken) { setValue(result[0].rawValue); setError(''); stop(); window.clearInterval(timer); } else setError(t.inviteError); } }, 400); }, 0); } catch { stop(); setError(t.camera); }
  };
  const countryNext = () => { if (!country) { setError(t.countryError); return; } const nextLocale = nationalityLocales[country]; if (nextLocale) setLocale(nextLocale); setError(''); setPhase('profile'); };
  const inviteNext = () => { if (!extractToken(value, 'team')) { setError(t.inviteError); return; } stop(); setError(''); setPhase('country'); };
  const join = async () => { const token = extractToken(value, 'team'); if (!name.trim()) { setError(t.nameError); return; } if (!country || !token) { setPhase(!country ? 'country' : 'invite'); setError(!country ? t.countryError : t.inviteError); return; } setLoading(true); setError(''); try { const member = await api.joinTodayTeam(token, { display_name: name.trim(), nationality_code: country, language_code: workerLocale }); setJoined(member); window.history.replaceState({}, '', `/team/${encodeURIComponent(token)}`); stop(); } catch { setError(t.inviteError); } finally { setLoading(false); } };
  if (joined) return <div className="mx-auto max-w-xl py-10 text-center sm:py-20"><span className="mx-auto flex h-24 w-24 items-center justify-center rounded-full bg-[#DDE9D8] text-deep"><Check className="h-12 w-12" /></span><h1 className="mt-6 text-3xl font-black">{t.joined}</h1><p className="mt-3 text-xl font-bold">{joined.display_name}</p><p className="mt-4 text-lg font-bold text-muted">{t.wait}</p></div>;
  if (phase === 'invite') return <div className="mx-auto max-w-2xl py-6 sm:py-12"><PageHeading title={t.inviteTitle} description={t.inviteDescription} action={<ActionButton className="shrink-0 whitespace-nowrap" variant="secondary" onClick={() => { stop(); go('role'); }}><ArrowLeft className="h-5 w-5" />{t.back}</ActionButton>} /><Panel><StatusBadge tone="blue">1 / 3</StatusBadge><ActionButton className="mt-5 w-full" variant="secondary" onClick={scan}><Camera className="h-6 w-6" />{scanning ? t.stop : t.scan}</ActionButton>{scanning && <video ref={video} muted playsInline className="mt-3 aspect-[4/3] w-full rounded-2xl bg-black object-cover" aria-label={t.scan} />}<label htmlFor="team-link" className="mt-5 block text-lg font-black">{t.link}</label><input id="team-link" value={value} onChange={(event) => setValue(event.target.value)} inputMode="url" className="mt-2 min-h-14 w-full rounded-2xl border border-deep/20 px-4 text-base font-bold outline-none focus:border-primary focus:ring-4 focus:ring-primary/20" placeholder="https://…/team/…" />{isMockApi && <div className="mt-4 rounded-2xl bg-[#FFF4CF] p-4"><p className="text-base font-bold text-[#654B16]">{t.testHelp}</p><p className="mt-2 break-all text-sm font-bold text-[#654B16]">{testTeamLink}</p><ActionButton className="mt-3 w-full" variant="quiet" onClick={() => { setValue(testTeamLink); setError(''); }}>{t.testLink}</ActionButton></div>}<ActionButton className="mt-5 w-full" onClick={inviteNext}>{t.next}<ArrowRight className="h-5 w-5" /></ActionButton>{error && <p role="alert" className="mt-4 text-base font-extrabold text-[#8A302B]">{error}</p>}</Panel></div>;
  if (phase === 'country') return <div className="mx-auto max-w-2xl py-6 sm:py-12"><PageHeading title={t.countryTitle} description={t.countryDescription} action={<ActionButton className="shrink-0 whitespace-nowrap" variant="secondary" onClick={() => { setError(''); setPhase('invite'); }}><ArrowLeft className="h-5 w-5" />{t.back}</ActionButton>} /><Panel><StatusBadge tone="blue">2 / 3</StatusBadge><label htmlFor="worker-country" className="mt-5 block text-lg font-black">{t.country}</label><div className="relative mt-2"><select id="worker-country" value={country} onChange={(event) => setCountry(event.target.value as NationalityCode)} className="min-h-14 w-full appearance-none rounded-2xl border border-deep/20 bg-white py-3 pl-4 pr-16 text-lg font-bold outline-none focus:border-primary focus:ring-4 focus:ring-primary/20"><option value="" disabled>Select country</option>{countries.map((item) => <option key={item.code} value={item.code}>{item.name}</option>)}</select><ChevronDown className="pointer-events-none absolute right-5 top-1/2 h-7 w-7 -translate-y-1/2 text-deep" aria-hidden="true" /></div><ActionButton className="mt-5 w-full" onClick={countryNext}>{t.next}<ArrowRight className="h-5 w-5" /></ActionButton>{error && <p role="alert" className="mt-4 text-base font-extrabold text-[#8A302B]">{error}</p>}</Panel></div>;
  return <div className="mx-auto max-w-2xl py-6 sm:py-12"><PageHeading title={t.profileTitle} description={t.profileDescription} action={<ActionButton className="shrink-0 whitespace-nowrap" variant="secondary" onClick={() => { setError(''); setPhase('country'); }}><ArrowLeft className="h-5 w-5" />{t.back}</ActionButton>} /><Panel><StatusBadge tone="blue">3 / 3</StatusBadge><span className="mt-5 flex h-16 w-16 items-center justify-center rounded-2xl bg-[#E2F2FF] text-[#236A9E]"><UserRound className="h-8 w-8" /></span><label htmlFor="worker-name" className="mt-6 block text-lg font-black">{t.name}</label><input id="worker-name" value={name} maxLength={30} autoComplete="nickname" autoFocus onChange={(event) => setName(event.target.value)} className="mt-2 min-h-14 w-full rounded-2xl border border-deep/20 px-4 text-lg font-bold outline-none focus:border-primary focus:ring-4 focus:ring-primary/20" placeholder={t.nameHint} /><ActionButton className="mt-5 w-full" disabled={loading} onClick={join}>{loading ? '…' : t.join}<ArrowRight className="h-5 w-5" /></ActionButton>{error && <p role="alert" className="mt-4 text-base font-extrabold text-[#8A302B]">{error}</p>}</Panel></div>;
}

function WorkerLatest({ assignment, go }: { assignment: WorkerAssignment; go: ScreenProps['go'] }) {
  const locale = assignment.language_code; const t = labels[locale]; const first = assignment.steps[0];
  return <><PageHeading title={t.latest} description={`v${assignment.version} · ${t.today}`} />{assignment.badge_codes.length > 0 && <div className="mb-4 flex flex-wrap gap-2">{assignment.badge_codes.map((badge) => <StatusBadge key={badge} tone="yellow">{badgeText(locale, badge)}</StatusBadge>)}</div>}<section className="mb-5 rounded-2xl bg-[#E5F0E0] p-6 sm:p-8"><StatusBadge>{languageNames[locale]}</StatusBadge><h1 className="mt-4 text-2xl font-black sm:text-3xl">{first?.title ?? t.today}</h1><div className="mt-5 grid gap-1 sm:grid-cols-2"><FactRow label={t.location} value={assignment.context.location_display} /><FactRow label={t.amount} value={assignment.context.quantity_display} /><FactRow label={t.deadline} value={assignment.context.deadline_display ?? '—'} /><FactRow label={t.note} value={assignment.context.notes ?? '—'} last /></div></section><div className="grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><Panel><PanelHeader title={t.today} aside={<StatusBadge tone="blue">{assignment.steps.length}</StatusBadge>} /><ol className="grid gap-3">{assignment.steps.map((step) => <li key={step.sequence} className="flex items-center gap-4 rounded-2xl bg-[#F5F8F3] p-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-deep font-black text-white">{step.sequence}</span><strong className="text-lg leading-7">{step.title}</strong></li>)}</ol>{assignment.context.safety.length > 0 && <div className="mt-5"><Callout><span className="flex gap-2 text-base"><ShieldAlert className="mt-1 h-5 w-5 shrink-0" />{assignment.context.safety.join(' · ')}</span></Callout></div>}</Panel><Panel className="self-start"><PanelHeader title={t.listen} aside={<Volume2 className="h-6 w-6 text-primary" />} />{first ? <><p className="mb-5 text-lg font-bold leading-8 text-muted">{first.description}</p><SpeakButton step={first} locale={locale} /><ActionButton className="mt-3 w-full" variant="secondary" onClick={() => go('worker-step')}>{t.view}<ArrowRight className="h-5 w-5" /></ActionButton></> : <Callout>{t.invalid}</Callout>}</Panel></div></>;
}

function WorkerStepView({ assignment, go }: { assignment: WorkerAssignment; go: ScreenProps['go'] }) {
  const locale = assignment.language_code; const t = labels[locale]; const [index, setIndex] = useState(0); const [videoFailed, setVideoFailed] = useState(false); const step = assignment.steps[Math.min(index, assignment.steps.length - 1)]; const video = step ? playableVideo(step) : null;
  useEffect(() => { setIndex(0); setVideoFailed(false); window.speechSynthesis.cancel(); }, [assignment.version]);
  useEffect(() => setVideoFailed(false), [index, video?.video_url]);
  if (!step) return <Callout>{t.invalid}</Callout>;
  return <><PageHeading title={`${stepNames[locale].step} ${index + 1} / ${assignment.steps.length}`} description={step.title} action={<ActionButton variant="secondary" onClick={() => go('worker-latest')}><ArrowLeft className="h-5 w-5" />{stepNames[locale].list}</ActionButton>} /><div className="grid gap-5 xl:grid-cols-[1.3fr_0.7fr]"><section>{video && !videoFailed ? <video key={video.video_url} controls playsInline className="aspect-video w-full rounded-2xl bg-deep object-cover" onError={() => setVideoFailed(true)}><source src={video.video_url} /><track kind="captions" src={captionsUrl(video.captions_text)} srcLang={locale} label={locale} default /></video> : <Callout safe><p className="text-lg">{t.fallback}</p></Callout>}<div className="mt-4 grid grid-cols-[auto_1fr_auto] gap-2"><ActionButton disabled={index === 0} variant="secondary" onClick={() => setIndex((value) => value - 1)}><ChevronLeft className="h-5 w-5" /><span className="hidden sm:inline">{t.prev}</span></ActionButton><SpeakButton step={step} locale={locale} /><ActionButton disabled={index === assignment.steps.length - 1} variant="secondary" onClick={() => setIndex((value) => value + 1)}><span className="hidden sm:inline">{t.next}</span><ChevronRight className="h-5 w-5" /></ActionButton></div></section><Panel className="self-start"><PanelHeader title={step.title} aside={<StatusBadge>v{assignment.version}</StatusBadge>} /><p className="text-xl font-extrabold leading-9">{step.description}</p>{video && <p className="mt-4 text-base font-bold text-muted">{video.captions_text}</p>}<div className="mt-6"><ProgressBar value={((index + 1) / assignment.steps.length) * 100} label="step progress" /></div>{index === assignment.steps.length - 1 && <ActionButton variant="quiet" className="mt-6 w-full" onClick={() => go('worker-latest')}><Check className="h-5 w-5" />{t.understood}</ActionButton>}</Panel></div></>;
}

function LinkError({ locale, code, retry }: { locale: WorkerLocale; code: string; retry?: () => void }) { const t = labels[locale]; const expired = code === 'LINK_EXPIRED'; const Icon = expired ? Clock3 : code === 'ACCESS_DENIED' ? Link2Off : AlertCircle; return <div className="mx-auto max-w-xl py-10 text-center sm:py-20"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-[#FFF0BF] text-[#805D09]"><Icon className="h-10 w-10" /></div><h1 className="mt-6 text-3xl font-black">{t.unavailable}</h1><p className="mt-4 text-lg font-bold leading-8 text-muted">{expired ? t.expired : t.invalid}</p>{retry && !expired && <ActionButton className="mt-6" onClick={retry}>{t.retry}</ActionButton>}</div>; }

export function WorkerScreenRouter({ screen, go, token, locale, entryLocale, setLocale }: WorkerScreenProps) {
  const [assignment, setAssignment] = useState<WorkerAssignment | null>(null); const [errorCode, setErrorCode] = useState(''); const [refresh, setRefresh] = useState(0); const [updated, setUpdated] = useState(false);
  useEffect(() => { if (screen === 'worker-entry') return; if (!token) { setAssignment(null); setErrorCode('ACCESS_DENIED'); return; } const load = () => api.getAssignment(token).then((next) => { setAssignment((current) => { if (current && next.version > current.version) { window.speechSynthesis.cancel(); setUpdated(true); } return !current || next.version >= current.version ? next : current; }); setLocale(next.language_code); setErrorCode(''); }).catch((reason) => { const code = reason instanceof ApiError ? reason.code : 'INTERNAL_ERROR'; if (code === 'LINK_EXPIRED' || code === 'ACCESS_DENIED') { setAssignment(null); window.speechSynthesis.cancel(); } setErrorCode(code); }); load(); const timer = window.setInterval(load, 5000); const focus = () => document.visibilityState === 'visible' && load(); document.addEventListener('visibilitychange', focus); window.addEventListener('focus', load); return () => { window.clearInterval(timer); document.removeEventListener('visibilitychange', focus); window.removeEventListener('focus', load); window.speechSynthesis.cancel(); }; }, [token, screen === 'worker-entry', refresh]);
  if (screen === 'worker-entry') return <WorkerEntry locale={entryLocale} workerLocale={locale} setLocale={setLocale} go={go} />;
  if (errorCode && !assignment) return <LinkError locale={locale} code={errorCode} retry={() => setRefresh((value) => value + 1)} />;
  if (!assignment) return <div className="h-64 animate-pulse rounded-2xl bg-sage/40" aria-label="loading" />;
  const t = labels[assignment.language_code];
  return <>{updated && <div role="status" aria-live="assertive" className="mb-5 rounded-2xl bg-[#173F24] p-5 text-lg font-black text-white">{t.updated}</div>}{errorCode && <div role="alert" className="mb-5 flex flex-col gap-3 rounded-2xl bg-[#FFF0BF] p-5 text-base font-extrabold text-[#654B16] sm:flex-row sm:items-center sm:justify-between"><span>{t.stale}</span><ActionButton variant="secondary" onClick={() => setRefresh((value) => value + 1)}>{t.retry}</ActionButton></div>}{screen === 'worker-step' ? <WorkerStepView key={assignment.version} assignment={assignment} go={go} /> : <WorkerLatest assignment={assignment} go={go} />}</>;
}
