import { AlertCircle, ArrowLeft, ArrowRight, Camera, Check, ChevronLeft, ChevronRight, Clock3, Link2Off, ShieldAlert, UserRound, Volume2 } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { api, ApiError } from './api';
import type { TeamMember, WorkerAssignment, WorkerBadgeCode, WorkerStep } from './contracts';
import type { AppScreen, ScreenProps, WorkerLocale } from './model';
import type { Locale } from '../types';
import { ActionButton, Callout, FactRow, PageHeading, Panel, PanelHeader, ProgressBar, StatusBadge } from './ScreenUI';

interface WorkerScreenProps extends ScreenProps { screen: AppScreen; token: string | null; locale: WorkerLocale; entryLocale: Locale; setLocale: (locale: WorkerLocale) => void; }
const labels = {
  vi: { latest: 'Công việc mới nhất', today: 'Công việc hôm nay', location: 'Địa điểm', amount: 'Số lượng', deadline: 'Hoàn thành', note: 'Ghi chú', safety: 'An toàn', listen: 'Nghe hướng dẫn', view: 'Xem từng bước', prev: 'Trước', next: 'Tiếp theo', understood: 'Đã hiểu', fallback: 'Không có video đã kiểm duyệt. Hãy đọc hoặc nghe hướng dẫn.', unavailable: 'Không thể mở đường dẫn', expired: 'Đường dẫn đã hết hạn. Hãy xin chủ nông trại gửi lại đường dẫn mới.', invalid: 'Không thể truy cập. Hãy kiểm tra đường dẫn hoặc hỏi chủ nông trại.', stale: 'Không thể kiểm tra hướng dẫn mới nhất. Nội dung bên dưới có thể đã cũ.', retry: 'Thử lại', updated: 'Có hướng dẫn mới. Hãy xem lại từ bước đầu tiên.', audioFailed: 'Không thể phát giọng nói. Hãy đọc nội dung bên dưới.', needs: 'Cần xác nhận với chủ nông trại', demo: 'NỘI DUNG DEMO', waiting: 'Hãy chờ chủ nông trại gửi hướng dẫn.' },
  ne: { latest: 'नयाँ काम', today: 'आजको काम', location: 'स्थान', amount: 'परिमाण', deadline: 'समय सीमा', note: 'टिप्पणी', safety: 'सुरक्षा', listen: 'निर्देशन सुन्नुहोस्', view: 'चरणहरू हेर्नुहोस्', prev: 'अघिल्लो', next: 'अर्को', understood: 'बुझें', fallback: 'जाँच गरिएको भिडियो छैन। निर्देशन पढ्नुहोस् वा सुन्नुहोस्।', unavailable: 'लिङ्क खोल्न सकिएन', expired: 'लिङ्कको म्याद सकिएको छ। खेत मालिकसँग नयाँ लिङ्क माग्नुहोस्।', invalid: 'पहुँच गर्न सकिएन। लिङ्क जाँच्नुहोस् वा खेत मालिकलाई सोध्नुहोस्।', stale: 'नयाँ निर्देशन जाँच्न सकिएन। तलको जानकारी पुरानो हुन सक्छ।', retry: 'फेरि प्रयास', updated: 'नयाँ निर्देशन आएको छ। पहिलो चरणदेखि फेरि हेर्नुहोस्।', audioFailed: 'आवाज बजाउन सकिएन। तलको निर्देशन पढ्नुहोस्।', needs: 'खेत मालिकसँग पुष्टि गर्नुहोस्', demo: 'डेमो सामग्री', waiting: 'खेत मालिकको निर्देशन पर्खनुहोस्।' },
};

const badgeText = (locale: WorkerLocale, badge: WorkerBadgeCode) => badge === 'NEEDS_CONFIRMATION' ? labels[locale].needs : labels[locale].demo;
const playableVideo = (step: WorkerStep) => step.video?.review_status === 'APPROVED' && step.video.safety_level === 'LOW' ? step.video : null;
const captionsUrl = (text: string) => `data:text/vtt;charset=utf-8,${encodeURIComponent(`WEBVTT\n\n00:00.000 --> 23:59.000\n${text.replace(/\n/g, ' ')}`)}`;

function SpeakButton({ step, locale, className = '' }: { step: WorkerStep; locale: WorkerLocale; className?: string }) {
  const [speaking, setSpeaking] = useState(false); const [failed, setFailed] = useState(false); const audio = useRef<HTMLAudioElement | null>(null);
  const browserSpeech = () => { if (!window.speechSynthesis) { setFailed(true); setSpeaking(false); return; } const speech = new SpeechSynthesisUtterance(step.description); speech.lang = locale === 'vi' ? 'vi-VN' : 'ne-NP'; speech.onend = () => setSpeaking(false); speech.onerror = () => { setSpeaking(false); setFailed(true); }; window.speechSynthesis.cancel(); window.speechSynthesis.speak(speech); };
  const play = async () => { setFailed(false); setSpeaking(true); window.speechSynthesis.cancel(); audio.current?.pause(); if (!step.audio_url) { browserSpeech(); return; } const next = new Audio(step.audio_url); audio.current = next; next.onended = () => setSpeaking(false); next.onerror = browserSpeech; try { await next.play(); } catch { browserSpeech(); } };
  useEffect(() => () => { audio.current?.pause(); window.speechSynthesis.cancel(); }, [step.sequence, step.description]);
  return <div className={className}><ActionButton className="w-full" onClick={play}><Volume2 className={`h-5 w-5 ${speaking ? 'animate-pulse' : ''}`} />{labels[locale].listen}</ActionButton>{failed && <p role="alert" className="mt-3 text-base font-extrabold text-[#8A302B]">{labels[locale].audioFailed}</p>}</div>;
}

const entryCopy = {
  ko: { firstTitle: '작업팀 찾기', firstDescription: '농장주의 QR을 스캔하고 안내 언어를 선택하세요.', profileTitle: '이름을 알려주세요', profileDescription: '농장주가 알아볼 수 있는 이름이나 별명을 적어주세요.', name: '이름 또는 별명', nameHint: '예: 응우옌', scan: 'QR 코드 스캔', stop: '카메라 닫기', link: '팀 참여 링크 또는 코드', next: '다음', back: '이전', join: '오늘 작업팀 들어가기', joined: '작업팀에 들어왔어요', wait: '농장주의 작업 지시를 기다려주세요.', camera: '카메라를 사용할 수 없습니다. 아래에 링크나 코드를 입력하세요.', firstError: '올바른 참여 코드를 확인해주세요.', nameError: '이름 또는 별명을 입력해주세요.' },
  vi: { firstTitle: 'Tìm nhóm làm việc', firstDescription: 'Quét mã QR của chủ nông trại và chọn ngôn ngữ hướng dẫn.', profileTitle: 'Cho chúng tôi biết tên của bạn', profileDescription: 'Nhập tên hoặc biệt danh để chủ nông trại nhận ra bạn.', name: 'Tên hoặc biệt danh', nameHint: 'Ví dụ: Nguyễn', scan: 'Quét mã QR', stop: 'Đóng camera', link: 'Đường dẫn hoặc mã tham gia', next: 'Tiếp theo', back: 'Quay lại', join: 'Tham gia nhóm hôm nay', joined: 'Bạn đã vào nhóm', wait: 'Hãy chờ chủ nông trại gửi hướng dẫn.', camera: 'Không thể dùng camera. Hãy nhập đường dẫn hoặc mã bên dưới.', firstError: 'Kiểm tra mã tham gia.', nameError: 'Hãy nhập tên hoặc biệt danh.' },
  ne: { firstTitle: 'काम टोली खोज्नुहोस्', firstDescription: 'खेत मालिकको QR स्क्यान गरी निर्देशन भाषा छान्नुहोस्।', profileTitle: 'तपाईंको नाम लेख्नुहोस्', profileDescription: 'खेत मालिकले चिन्न सक्ने नाम वा उपनाम लेख्नुहोस्।', name: 'नाम वा उपनाम', nameHint: 'उदाहरण: रमेश', scan: 'QR कोड स्क्यान', stop: 'क्यामेरा बन्द', link: 'टोली लिङ्क वा कोड', next: 'अर्को', back: 'अघिल्लो', join: 'आजको टोलीमा सामेल', joined: 'तपाईं टोलीमा सामेल हुनुभयो', wait: 'खेत मालिकको निर्देशन पर्खनुहोस्।', camera: 'क्यामेरा चलाउन सकिएन। तल लिङ्क वा कोड लेख्नुहोस्।', firstError: 'सहभागिता कोड जाँच्नुहोस्।', nameError: 'नाम वा उपनाम लेख्नुहोस्।' },
};
const extractToken = (value: string, kind: 'team' | 'work') => value.trim().match(new RegExp(`/${kind === 'team' ? 'team' : 'w'}/([^/?#]+)`))?.[1] ?? (value.trim().length >= 32 ? value.trim() : '');

function WorkerEntry({ locale, workerLocale }: { locale: Locale; workerLocale: WorkerLocale }) {
  const directToken = extractToken(window.location.href, 'team'); const [phase, setPhase] = useState<'team' | 'profile'>('team'); const [value, setValue] = useState(directToken); const [name, setName] = useState(''); const [error, setError] = useState(''); const [joined, setJoined] = useState<TeamMember | null>(null); const [scanning, setScanning] = useState(false); const [loading, setLoading] = useState(false); const video = useRef<HTMLVideoElement | null>(null); const stream = useRef<MediaStream | null>(null); const t = entryCopy[locale];
  const stop = () => { stream.current?.getTracks().forEach((track) => track.stop()); stream.current = null; setScanning(false); };
  useEffect(() => stop, []);
  const scan = async () => {
    if (scanning) { stop(); return; }
    const Detector = (window as unknown as { BarcodeDetector?: new (options: { formats: string[] }) => { detect(source: HTMLVideoElement): Promise<Array<{ rawValue: string }>> } }).BarcodeDetector;
    if (!Detector || !navigator.mediaDevices?.getUserMedia) { setError(t.camera); return; }
    try { setError(''); const media = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } }); stream.current = media; setScanning(true); window.setTimeout(async () => { if (!video.current) return; video.current.srcObject = media; await video.current.play(); const detector = new Detector({ formats: ['qr_code'] }); const timer = window.setInterval(async () => { if (!video.current || !stream.current) { window.clearInterval(timer); return; } const result = await detector.detect(video.current).catch(() => []); if (result[0]?.rawValue) { const workToken = extractToken(result[0].rawValue, 'work'); const teamToken = extractToken(result[0].rawValue, 'team'); if (result[0].rawValue.includes('/w/') && workToken) window.location.href = `/w/${encodeURIComponent(workToken)}`; else if (teamToken) { setValue(teamToken); stop(); window.clearInterval(timer); } } }, 400); }, 0); } catch { stop(); setError(t.camera); }
  };
  const next = () => { const token = extractToken(value, 'team'); if (!token) { setError(t.firstError); return; } stop(); setError(''); setPhase('profile'); };
  const join = async () => { const token = extractToken(value, 'team'); if (!name.trim()) { setError(t.nameError); return; } if (!token) { setPhase('team'); setError(t.firstError); return; } setLoading(true); setError(''); try { setJoined(await api.joinTodayTeam(token, { display_name: name.trim(), language_code: workerLocale })); stop(); window.location.assign('/worker/my'); } catch { setError(t.firstError); } finally { setLoading(false); } };
  if (joined) return <div className="mx-auto max-w-xl py-10 text-center sm:py-20"><span className="mx-auto flex h-24 w-24 items-center justify-center rounded-full bg-[#DDE9D8] text-deep"><Check className="h-12 w-12" /></span><h1 className="mt-6 text-3xl font-black">{t.joined}</h1><p className="mt-3 text-xl font-bold">{joined.display_name}</p><p className="mt-4 text-lg font-bold text-muted">{t.wait}</p></div>;
  if (phase === 'profile') return <div className="mx-auto max-w-2xl py-6 sm:py-12"><PageHeading title={t.profileTitle} description={t.profileDescription} action={<ActionButton variant="secondary" onClick={() => { setError(''); setPhase('team'); }}><ArrowLeft className="h-5 w-5" />{t.back}</ActionButton>} /><Panel><span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-[#E2F2FF] text-[#236A9E]"><UserRound className="h-8 w-8" /></span><label htmlFor="worker-name" className="mt-6 block text-lg font-black">{t.name}</label><input id="worker-name" value={name} maxLength={30} autoComplete="nickname" autoFocus onChange={(event) => setName(event.target.value)} className="mt-2 min-h-14 w-full rounded-2xl border border-deep/20 px-4 text-lg font-bold outline-none focus:border-primary focus:ring-4 focus:ring-primary/20" placeholder={t.nameHint} /><ActionButton className="mt-5 w-full" disabled={loading} onClick={join}>{loading ? '…' : t.join}<ArrowRight className="h-5 w-5" /></ActionButton>{error && <p role="alert" className="mt-4 text-base font-extrabold text-[#8A302B]">{error}</p>}</Panel></div>;
  return <div className="mx-auto max-w-2xl py-6 sm:py-12"><PageHeading title={t.firstTitle} description={t.firstDescription} /><Panel><ActionButton className="w-full" variant="secondary" onClick={scan}><Camera className="h-6 w-6" />{scanning ? t.stop : t.scan}</ActionButton>{scanning && <video ref={video} muted playsInline className="mt-3 aspect-[4/3] w-full rounded-2xl bg-black object-cover" aria-label={t.scan} />}<label htmlFor="team-link" className="mt-5 block text-lg font-black">{t.link}</label><input id="team-link" value={value} onChange={(event) => setValue(event.target.value)} inputMode="url" className="mt-2 min-h-14 w-full rounded-2xl border border-deep/20 px-4 text-base font-bold outline-none focus:border-primary focus:ring-4 focus:ring-primary/20" placeholder="https://…/team/…" /><ActionButton className="mt-5 w-full" onClick={next}>{t.next}<ArrowRight className="h-5 w-5" /></ActionButton>{error && <p role="alert" className="mt-4 text-base font-extrabold text-[#8A302B]">{error}</p>}</Panel></div>;
}

function WorkerLatest({ assignment, go }: { assignment: WorkerAssignment; go: ScreenProps['go'] }) {
  const locale = assignment.language_code; const t = labels[locale]; const first = assignment.steps[0];
  return <><PageHeading title={t.latest} description={`v${assignment.version} · ${t.today}`} />{assignment.badge_codes.length > 0 && <div className="mb-4 flex flex-wrap gap-2">{assignment.badge_codes.map((badge) => <StatusBadge key={badge} tone="yellow">{badgeText(locale, badge)}</StatusBadge>)}</div>}<section className="mb-5 rounded-2xl bg-[#E5F0E0] p-6 sm:p-8"><StatusBadge>{locale === 'vi' ? 'Tiếng Việt' : 'नेपाली'}</StatusBadge><h1 className="mt-4 text-2xl font-black sm:text-3xl">{first?.title ?? t.today}</h1><div className="mt-5 grid gap-1 sm:grid-cols-2"><FactRow label={t.location} value={assignment.context.location_display} /><FactRow label={t.amount} value={assignment.context.quantity_display} /><FactRow label={t.deadline} value={assignment.context.deadline_display ?? '—'} /><FactRow label={t.note} value={assignment.context.notes ?? '—'} last /></div></section><div className="grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><Panel><PanelHeader title={t.today} aside={<StatusBadge tone="blue">{assignment.steps.length}</StatusBadge>} /><ol className="grid gap-3">{assignment.steps.map((step) => <li key={step.sequence} className="flex items-center gap-4 rounded-2xl bg-[#F5F8F3] p-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-deep font-black text-white">{step.sequence}</span><strong className="text-lg leading-7">{step.title}</strong></li>)}</ol>{assignment.context.safety.length > 0 && <div className="mt-5"><Callout><span className="flex gap-2 text-base"><ShieldAlert className="mt-1 h-5 w-5 shrink-0" />{assignment.context.safety.join(' · ')}</span></Callout></div>}</Panel><Panel className="self-start"><PanelHeader title={t.listen} aside={<Volume2 className="h-6 w-6 text-primary" />} />{first ? <><p className="mb-5 text-lg font-bold leading-8 text-muted">{first.description}</p><SpeakButton step={first} locale={locale} /><ActionButton className="mt-3 w-full" variant="secondary" onClick={() => go('worker-step')}>{t.view}<ArrowRight className="h-5 w-5" /></ActionButton></> : <Callout>{t.invalid}</Callout>}</Panel></div></>;
}

function WorkerStepView({ assignment, go }: { assignment: WorkerAssignment; go: ScreenProps['go'] }) {
  const locale = assignment.language_code; const t = labels[locale]; const [index, setIndex] = useState(0); const [videoFailed, setVideoFailed] = useState(false); const step = assignment.steps[Math.min(index, assignment.steps.length - 1)]; const video = step ? playableVideo(step) : null;
  useEffect(() => { setIndex(0); setVideoFailed(false); window.speechSynthesis.cancel(); }, [assignment.version]);
  useEffect(() => setVideoFailed(false), [index, video?.video_url]);
  if (!step) return <Callout>{t.invalid}</Callout>;
  return <><PageHeading title={`${locale === 'vi' ? 'Bước' : 'चरण'} ${index + 1} / ${assignment.steps.length}`} description={step.title} action={<ActionButton variant="secondary" onClick={() => go('worker-latest')}><ArrowLeft className="h-5 w-5" />{locale === 'vi' ? 'Danh sách' : 'सूची'}</ActionButton>} /><div className="grid gap-5 xl:grid-cols-[1.3fr_0.7fr]"><section>{video && !videoFailed ? <video key={video.video_url} controls playsInline className="aspect-video w-full rounded-2xl bg-deep object-cover" onError={() => setVideoFailed(true)}><source src={video.video_url} /><track kind="captions" src={captionsUrl(video.captions_text)} srcLang={locale} label={locale} default /></video> : <Callout safe><p className="text-lg">{t.fallback}</p></Callout>}<div className="mt-4 grid grid-cols-[auto_1fr_auto] gap-2"><ActionButton disabled={index === 0} variant="secondary" onClick={() => setIndex((value) => value - 1)}><ChevronLeft className="h-5 w-5" /><span className="hidden sm:inline">{t.prev}</span></ActionButton><SpeakButton step={step} locale={locale} /><ActionButton disabled={index === assignment.steps.length - 1} variant="secondary" onClick={() => setIndex((value) => value + 1)}><span className="hidden sm:inline">{t.next}</span><ChevronRight className="h-5 w-5" /></ActionButton></div></section><Panel className="self-start"><PanelHeader title={step.title} aside={<StatusBadge>v{assignment.version}</StatusBadge>} /><p className="text-xl font-extrabold leading-9">{step.description}</p>{video && <p className="mt-4 text-base font-bold text-muted">{video.captions_text}</p>}<div className="mt-6"><ProgressBar value={((index + 1) / assignment.steps.length) * 100} label="step progress" /></div>{index === assignment.steps.length - 1 && <ActionButton variant="quiet" className="mt-6 w-full" onClick={() => go('worker-latest')}><Check className="h-5 w-5" />{t.understood}</ActionButton>}</Panel></div></>;
}

function LinkError({ locale, code, retry }: { locale: WorkerLocale; code: string; retry?: () => void }) { const t = labels[locale]; const expired = code === 'LINK_EXPIRED'; const Icon = expired ? Clock3 : code === 'ACCESS_DENIED' ? Link2Off : AlertCircle; return <div className="mx-auto max-w-xl py-10 text-center sm:py-20"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-[#FFF0BF] text-[#805D09]"><Icon className="h-10 w-10" /></div><h1 className="mt-6 text-3xl font-black">{t.unavailable}</h1><p className="mt-4 text-lg font-bold leading-8 text-muted">{expired ? t.expired : t.invalid}</p>{retry && !expired && <ActionButton className="mt-6" onClick={retry}>{t.retry}</ActionButton>}</div>; }

export function WorkerScreenRouter({ screen, go, token, locale, entryLocale, setLocale }: WorkerScreenProps) {
  const [assignment, setAssignment] = useState<WorkerAssignment | null>(null); const [errorCode, setErrorCode] = useState(''); const [refresh, setRefresh] = useState(0); const [updated, setUpdated] = useState(false); const [waiting, setWaiting] = useState(false); const isTeamMember = token === '__team_member__';
  useEffect(() => { if (screen === 'worker-entry') return; if (!token) { setAssignment(null); setErrorCode('ACCESS_DENIED'); return; } const receive = (next: WorkerAssignment | null) => { setWaiting(!next && isTeamMember); if (!next) { setAssignment(null); setErrorCode(''); return; } setAssignment((current) => { if (current && next.version > current.version) { window.speechSynthesis.cancel(); setUpdated(true); } return !current || next.version >= current.version ? next : current; }); setLocale(next.language_code); setErrorCode(''); }; const load = () => (isTeamMember ? api.getMyTodayAssignments().then((items) => receive(items[0] ?? null)) : api.getAssignment(token).then(receive)).catch((reason) => { const code = reason instanceof ApiError ? reason.code : 'INTERNAL_ERROR'; if (code === 'LINK_EXPIRED' || code === 'ACCESS_DENIED') { setAssignment(null); window.speechSynthesis.cancel(); } setWaiting(false); setErrorCode(code); }); load(); const timer = window.setInterval(load, 5000); const focus = () => document.visibilityState === 'visible' && load(); document.addEventListener('visibilitychange', focus); window.addEventListener('focus', load); return () => { window.clearInterval(timer); document.removeEventListener('visibilitychange', focus); window.removeEventListener('focus', load); window.speechSynthesis.cancel(); }; }, [token, screen === 'worker-entry', refresh, isTeamMember, setLocale]);
  if (screen === 'worker-entry') return <WorkerEntry locale={entryLocale} workerLocale={locale} />;
  if (errorCode && !assignment) return <LinkError locale={locale} code={errorCode} retry={() => setRefresh((value) => value + 1)} />;
  if (waiting) return <div className="mx-auto max-w-xl py-10 text-center sm:py-20"><span className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-[#DDE9D8] text-deep"><Clock3 className="h-10 w-10" /></span><h1 className="mt-6 text-3xl font-black">{labels[locale].today}</h1><p className="mt-4 text-lg font-bold text-muted">{labels[locale].waiting}</p><ActionButton className="mt-6" variant="secondary" onClick={() => setRefresh((value) => value + 1)}>{labels[locale].retry}</ActionButton></div>;
  if (!assignment) return <div className="h-64 animate-pulse rounded-2xl bg-sage/40" aria-label="loading" />;
  const t = labels[assignment.language_code];
  return <>{updated && <div role="status" aria-live="assertive" className="mb-5 rounded-2xl bg-[#173F24] p-5 text-lg font-black text-white">{t.updated}</div>}{errorCode && <div role="alert" className="mb-5 flex flex-col gap-3 rounded-2xl bg-[#FFF0BF] p-5 text-base font-extrabold text-[#654B16] sm:flex-row sm:items-center sm:justify-between"><span>{t.stale}</span><ActionButton variant="secondary" onClick={() => setRefresh((value) => value + 1)}>{t.retry}</ActionButton></div>}{screen === 'worker-step' ? <WorkerStepView key={assignment.version} assignment={assignment} go={go} /> : <WorkerLatest assignment={assignment} go={go} />}</>;
}
